/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package area.netbooks1;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlumnosET20
 */
public class Stock extends javax.swing.JFrame {

    Conexcion_BD enlace = new Conexcion_BD();
    Connection conect = enlace.Conectar();
    
    public Stock() {
        initComponents();
    }
    
    public void mostrardatos(){
        DefaultTableModel tablitastock = new DefaultTableModel();
       tablitastock.addColumn("ID");
       tablitastock.addColumn("Codigo de barras");
       tablitastock.addColumn("Estado");
       tablitastock.addColumn("Observaciones");
       Tablastock.setModel(tablitastock);
       Statement vertablastock;
       String [] datos_stock = new String [4];
       try {
           vertablastock = conect.createStatement();
           ResultSet mostrarstock = vertablastock.executeQuery("SELECT * FROM stock");
           while (mostrarstock.next()){
                datos_stock[0] = mostrarstock.getString(1);
                datos_stock[1] = mostrarstock.getString(2);
                datos_stock[2] = mostrarstock.getString(3);
                datos_stock[3] = mostrarstock.getString(4);
                tablitastock.addRow(datos_stock);
           }
       }
        catch (SQLException e) {
            
        }

        Tablastock.setModel(tablitastock);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tablastock = new javax.swing.JTable();
        Boton_Volver2 = new javax.swing.JButton();
        Boton_Modificar1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Stocks de las computadoras");

        Tablastock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        Tablastock.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                TablastockAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(Tablastock);

        Boton_Volver2.setText("Volver");
        Boton_Volver2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Volver2ActionPerformed(evt);
            }
        });

        Boton_Modificar1.setText("Modificar");
        Boton_Modificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Modificar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(329, 329, 329)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 852, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(419, 419, 419)
                        .addComponent(Boton_Volver2)
                        .addGap(18, 18, 18)
                        .addComponent(Boton_Modificar1)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Volver2)
                    .addComponent(Boton_Modificar1))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Boton_Volver2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Volver2ActionPerformed
     this.setVisible(false);
     Main main = new Main();
     main.setVisible(true);
    }//GEN-LAST:event_Boton_Volver2ActionPerformed

    private void TablastockAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_TablastockAncestorAdded
   mostrardatos();
    }//GEN-LAST:event_TablastockAncestorAdded

    private void Boton_Modificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Modificar1ActionPerformed
        int fila = Tablastock.getSelectedRow();

        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el registro antes de apretar el botón");
        }

        String ID = Tablastock.getValueAt(fila, 0).toString();
        String Estado = Tablastock.getValueAt(fila, 3).toString();
        String Obser = Tablastock.getValueAt(fila, 2).toString();

        try {
            PreparedStatement actu = conect.prepareStatement("UPDATE stock SET ID='" + ID + "',Estado='" + Estado + "',Observaciones='" + Obser + "'WHERE Cod_Barra='" + fila + "'");
            actu.executeUpdate();
            mostrardatos();
        } catch (SQLException e) {

            JOptionPane.showMessageDialog(null, e + "No se pudo actualizar los datos");
        }
        if (fila < 0) {
            JOptionPane.showMessageDialog(null, "Seleccione el registro antes de apretar el botón");
        } else {
            JOptionPane.showMessageDialog(null, "¡Registro actualizado!");
        }
    }//GEN-LAST:event_Boton_Modificar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Boton_Modificar1;
    private javax.swing.JButton Boton_Volver2;
    private javax.swing.JTable Tablastock;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
